FROM node:18-alpine AS builder
WORKDIR /app
COPY src/main/frontend/package*.json .
RUN npm install --legacy-peer-deps
COPY src/main/frontend .
RUN npm run build

FROM nginx:1.25-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY src/main/frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
