version: '3.8'

services:
  backend:
    container_name: buysell-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/buysell_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - buysell-network
    depends_on:
      db:
        condition: service_started

  frontend:
    container_name: buysell-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - buysell-network
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: buysell-db
    environment:
      POSTGRES_DB: buysell_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - buysell-network

networks:
  buysell-network:
    name: buysell_application_buysell-network
    driver: bridge

volumes:
  db-data: