name: Docker Build and Deploy to Render

on:
  push:
    branches: [ "master" ]  # Триггер на коммиты в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Загрузка кода
      - uses: actions/checkout@v4

      # Шаг 2: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 3: Сборка и загрузка Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Путь к Dockerfile
          push: true  # Автоматически загружать образ в Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/buy-sell-app:latest  # Тег образа

      # Шаг 4: Деплой на Render.com
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          type: docker  # Тип деплоя — Docker
          dockerImage: ${{ secrets.DOCKER_HUB_USERNAME }}/buy-sell-app:latest  # Имя образа