name: Docker Build and Deploy Fullstack to Render

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Загрузка кода
      - uses: actions/checkout@v4

      # 2. Проверка структуры (для отладки)
      - name: Verify project structure
        run: |
          ls -la
          ls -la src/main/
          ls -la src/main/frontend/

      # 3. Сборка фронтенда
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build frontend
        run: |
          cd src/main/frontend
          npm install
          npm run build
        working-directory: ./src/main/frontend

      # 4. Сборка бэкенда
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package -DskipTests

      # 5. Логин в Docker Hub
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 6. Сборка фронтенд-образа
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: src/main/frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          file: src/main/frontend/Dockerfile.front

      # 7. Сборка бэкенд-образа
      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo-deployment:latest
          file: Dockerfile

      # 8. Деплой на Render
      - name: Deploy Backend
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/vnd.render+json; version=2021-06-01" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"

      - name: Deploy Frontend
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/vnd.render+json; version=2021-06-01" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys"