name: Docker Build and Deploy Fullstack to Render

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Загрузка кода
      - uses: actions/checkout@v4

      # 4. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5. Сборка и пуш Docker-образа для фронтенда (используем Dockerfile.front)
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          file: Dockerfile.front  # Указали кастомный путь к Dockerfile

      # 6. Сборка и пуш Docker-образа для бэкенда (тег demo-deployment)
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo-deployment:latest  # Имя образа как вам нужно
          file: Dockerfile

      # 7. Деплой бэкенда на Render
      - name: Trigger Backend Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/vnd.render+json; version=2021-06-01" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"  # Секрет для бэкенда

      # 8. Деплой фронтенда на Render
      - name: Trigger Frontend Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/vnd.render+json; version=2021-06-01" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys"  # Секрет для фронтенда